name: llm_ir_search
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - tk
  - pip:
      - arxiv
      - langchain
      - langchain-core
      - langchain-openai
      - pydantic>=2
      - openai
